### ISSUE TITLE
EE 11 Platform TCK Persistence (JPA) TCK runner `appclient` test EAR archive must be able to deploy to both Application Client and Platform implementation

### ISSUE THREAD

**Issue by scottmarlow** [OmniFish-EE/arquillian-container-glassfish#4]
Currently, the https://github.com/scottmarlow/jakartaee-tck/tree/correct_jpa_sunappclientxml glassfish-runner/jpa-platform-tck tests are failing due to:

> STATUS:Failed.Test run in stateless3 vehicle failed.
>         at com.sun.ts.tests.common.vehicle.stateless3.Stateless3VehicleRunner.run(Stateless3VehicleRunner.java:41)
>         at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:128)
>         at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:494)
>         at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:232)
>         at com.sun.ts.lib.harness.EETest.run(EETest.java:296)
>         at ee.jakarta.tck.persistence.core.StoredProcedureQuery.Client1.main(Client1.java:67)
> Caused by: javax.naming.NameNotFoundException: No object bound for java:comp/env/ejb/Stateless3VehicleBean
>         at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:135)
>         at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:818)

With earlier testing with WildFly via the https://github.com/scottmarlow/wildfly-ee11-tck-runner/blob/jpa3 changes, I could see that with the appclient protocol, we started deployments on both appclient + platform impl as per log output:

> Wildfly ./appclient/log/appclient.log
> 024-10-04 13:48:40,126 INFO [[org.jboss.as](http://org.jboss.as/).server.deployment] (MSC service thread 1-3) WFLYSRV0027: Starting deployment of "jpa_core_EntityGraph_appmanaged_vehicles.ear" (runtime-name: "jp
> a_core_EntityGraph_appmanaged_vehicles.ear")

> WildFly ./standalone/log/server.log
> 2024-10-04 13:48:35,535 INFO [[org.jboss.as](http://org.jboss.as/).server.deployment] (MSC service thread 1-6) WFLYSRV0027: Starting deployment of "jpa_core_EntityGraph_appmanaged_vehicles.ear" (runtime-name: "jp
> a_core_EntityGraph_appmanaged_vehicles.ear")

How can we achieve the same with https://github.com/OmniFish-EE/arquillian-container-glassfish?

**Comment by scottmarlow** [comment]
I tried updating the Platform TCK GlassFish runner as follows but we still didn't start the GlassFish Platform implementation (only the app client container was started which does deploy the ear but we need the Platform impl  also):

```
git diff
diff --git a/glassfish-runner/jpa-platform-tck/src/test/resources/appclient-arquillian.xml b/glassfish-runner/jpa-platform-tck/src/test/resources/appclient-arquillian.xml
index 01110395e..85469a65e 100644
--- a/glassfish-runner/jpa-platform-tck/src/test/resources/appclient-arquillian.xml
+++ b/glassfish-runner/jpa-platform-tck/src/test/resources/appclient-arquillian.xml
@@ -63,6 +63,12 @@
             <property name="trace">true</property>
             <property name="clientTimeout">20000</property>
         </protocol>
+        <protocol type="javatest">
+            <property name="trace">true</property>
+            <property name="workDir">/tmp</property>
+            <property name="tsJteFile">jakartaeetck/bin/ts.jte</property>
+            <property name="tsSqlStmtFile">sql/derby/derby.dml.sql</property>
+        </protocol>
     </container>
   </group>

```

**Comment by arjantijms** [comment]
> I could see that with the appclient protocol, we started deployments on both appclient + platform impl as per log output:

I'd have to look into that. Does the WildFly Arquillian container (connector) have special logic to recognize the appclient protocol? I mean, what code in the scenario you mentioned does the appclient + platform deployment?

In the GlassFish Arquillian container, starting GlassFish and deploying an archive to it happens e.g. here:

https://github.com/OmniFish-EE/arquillian-container-glassfish/blob/main/glassfish-managed/src/main/java/org/omnifaces/arquillian/container/glassfish/managed/GlassFishManagedDeployableContainer.java#L126

At the moment that code knows nothing about the app client container.

**Comment by scottmarlow** [comment]
One part is in the [appclient-arquillian.xml](https://github.com/jakartaredhat/wildfly-ee11-tck-runner/blob/db789e1e28829d465640a9b35af24ef17885b8ea/src/test/resources/javatest-appclient-arquillian.xml#L26)  which has:

>        <protocol type="appclient">
>            <property name="runClient">true</property>
>            <property name="runAsVehicle">true</property>
>            <property name="clientEarDir">target/appclient</property>
>            <property name="clientCmdLineString">${jboss.home}/bin/appclient.sh;-y=${project.build.testOutputDirectory}/appclient.yml:${project.build.testOutputDirectory}/derby.yml;${clientEarDir}/${vehicleArchiveName}.ear#${vehicleArchiveName}_client.jar</property>

**Comment by jamezp** [comment]
The WildFly Arquillian adapter does have some support for an appclient. However, it's not used when running the TCK. @starksm64 created the new protocol in the platform-tck. 

@scottmarlow are there instructions somewhere on how to run this? I can give it a try tomorrow. I assume this is the file that needs to be looked at https://github.com/scottmarlow/jakartaee-tck/blob/59c3ad5f17bbd7ecf674b92d6183f834e9a43917/glassfish-runner/jpa-platform-tck/src/test/resources/appclient-arquillian.xml#L20.

**Comment by scottmarlow** [comment]
General background info from EE 10 porting kit code links that dealt with app client deployment:
- https://github.com/jakartaee/platform-tck/blob/10.0.x/src/com/sun/ts/lib/porting/TSDeploymentInterface.java#L156 defines the TCK porting kit getAppClientArgs() `to get any additional test specific arguments that must be passed to the application client container class`
- https://github.com/jakartaee/platform-tck/blob/10.0.x/src/com/sun/ts/lib/implementation/sun/javaee/glassfish/AutoDeployment.java#L324 has getAppClientArgs()
- https://github.com/jakartaee/platform-tck/blob/10.0.x/src/com/sun/ts/lib/implementation/sun/javaee/SunRIDeployment14.java#L711 also has getAppClientArgs()

**Comment by scottmarlow** [comment]
> The WildFly Arquillian adapter does have some support for an appclient. However, it's not used when running the TCK. @starksm64 created the new protocol in the platform-tck.
> 
> @scottmarlow are there instructions somewhere on how to run this? I can give it a try tomorrow. I assume this is the file that needs to be looked at https://github.com/scottmarlow/jakartaee-tck/blob/59c3ad5f17bbd7ecf674b92d6183f834e9a43917/glassfish-runner/jpa-platform-tck/src/test/resources/appclient-arquillian.xml#L20.

Yes, instructions to run with Podman are on https://github.com/jakartaee/platform-tck/wiki/EE-11-Platform-TCK-testing-with-Podman

Please note that the https://github.com/scottmarlow/jakartaee-tck/tree/correct_jpa_sunappclientxml branch should be used for actual testing, so be sure to first switch to that and build the TCK, then run from `glassfish-runner/jpa-platform-tck` as instructions state.

**Comment by scottmarlow** [comment]
As James Perkins + Scott Stark mentioned, the GlassFish Application Client container is indeed running as part of the Junit/Maven process.  This issue can be closed now.
